# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('coordinate', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('privacy', models.BooleanField()),
                ('meetingID', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_at', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='at', to='RendezWho.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_Entry',
            fields=[
                ('entryID', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=50)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('connections', models.ManyToManyField(related_name='friends', to='RendezWho.UserApp')),
            ],
        ),
        migrations.AddField(
            model_name='schedule_entry',
            name='has',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rqsts', to='RendezWho.UserApp',null=True),
        ),
        migrations.AddField(
            model_name='schedule_entry',
            name='located',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='RendezWho.Location',null=True),
        ),
        migrations.AddField(
            model_name='schedule_entry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns', to='RendezWho.UserApp',null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='RendezWho.UserApp'),
        ),
    ]
