# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRequest',
            fields=[
                ('reqID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meetingID', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('privacy', models.BooleanField()),
                ('approved', models.BooleanField(default=False)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_at', models.CharField(max_length=50)),
                ('end_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_Entry',
            fields=[
                ('entryID', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=50)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('located', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('connections', models.ManyToManyField(related_name='_userapp_connections_+', to='RendezWho.UserApp')),
            ],
        ),
        migrations.AddField(
            model_name='schedule_entry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns', to='RendezWho.UserApp'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='RendezWho.UserApp'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rqsts', to='RendezWho.UserApp'),
        ),
        migrations.AddField(
            model_name='crequest',
            name='reqReceiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crequest',
            name='reqSender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='crequest',
            unique_together=set([('reqSender', 'reqReceiver')]),
        ),
    ]
