# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RendezWho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='connections',
            field=models.ManyToManyField(related_name='_userapp_connections_+', to='RendezWho.UserApp'),
        ),
    ]
