# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RendezWho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_at',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='schedule_entry',
            name='activity',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='schedule_entry',
            name='located',
            field=models.CharField(max_length=500),
        ),
    ]
