# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RendezWho', '0002_auto_20170420_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_entry',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule_entry',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
