# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RendezWho', '0004_auto_20170419_1449'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crequest',
            unique_together=set([('reqSender', 'reqReceiver')]),
        ),
    ]
